{% set name = "pympler" %}
{% set version = "0.8" %}
{% set sha256 = "e53e8b6ce632900f3eb3bb3c7b751386cec0084843a30085482c628492de2adc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
#  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  source_files:
    - test/*
  commands:
    - python test/runtest.py

about:
  home: https://github.com/pympler/pympler
  license: Apache-2
  license_family: Apache
  license_file: LICENSE
  summary: 'Development tool to measure, monitor and analyze the memory
  behavior of Python objects in a running Python application. '
  description: |
    A development tool to measure, monitor and analyze the memory
    behavior of Python objects.
  doc_url: http://pythonhosted.org/Pympler/
  dev_url: https://github.com/pympler/pympler

extra:
  recipe-maintainers:
    - CJ-Wright
